version: '3.4'

services:
  zk1:
    image: zookeeper:3.4.14
    container_name: zk1
    hostname: zk1
    restart: always
    ports:
      - 2181:2181
    networks:
      - mynet

  # zk1:
  #   image: zookeeper
  #   container_name: zk1
  #   restart: always
  #   ports:
  #     - 2181:2181
  #   environment:
  #     ZOO_MY_ID: 1
  #     ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  #   networks:
  #     - mynet

  # zk2:
  #   image: zookeeper
  #   container_name: zk2
  #   restart: always
  #   ports:
  #     - 2182:2181
  #   environment:
  #     ZOO_MY_ID: 2
  #     ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
  #   networks:
  #     - mynet

  # zk3:
  #   image: zookeeper
  #   container_name: zk3
  #   restart: always
  #   ports:
  #     - 2183:2181
  #   environment:
  #     ZOO_MY_ID: 3
  #     ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
  #   networks:
  #     - mynet

  dubbo-admin:
    image: elijah/dubbo-admin:0.2.0
    container_name: dubbo-admin
    restart: always
    environment: 
      - ZOOKEEPER_HOST=zookeeper://zk1
    external_links: 
      - zk1:zk1
    depends_on:
      - zk1
    ports:
      - "7001:8080"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
  